export {default as Hero} from "./Hero"
export {default as Highlight} from "./Highlight"
export {default as Navbar} from "./Navbar"
export {default as Features} from "./Features"
export {default as Model} from "./Model"
export {default as How_It_Works} from "./How_It_Works"
export {default as Footer} from "./Footer"
